___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

from scipy import stats
from pandas import Series, DataFrame

#### 2. Create an array from my_list=[5,10,15,20,25]

In [4]:
my_list = [5, 10, 15, 20, 25]

arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

__Solution-1__

In [5]:
arr1 = np.zeros([5, 5])  # w/ square brackets

arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

__Solution-2__  

In [6]:
np.zeros((5, 5))   # w/ parenthesis

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

__Solution-1__

In [7]:
arr2 = np.ones([4, 4], dtype=int)

arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

__Solution-2__

In [8]:
arr = np.array(my_list)

# arr21 = arr1[:-1,:-1] + 1

arr21 = np.array((arr1[:-1,:-1] + 1), dtype=int)

arr21

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

__Solution-1__

In [9]:
arr3 = arr2 * 7
arr3

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

__Solution-2__

In [10]:
arr32 = arr2 + 6
arr32

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create their previous array above by full() method

In [11]:
arr4 = np.full([4, 4], 7)
arr4

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

__Solution-1__

In [12]:
arr7 = np.arange(2, 17, 2)
arr7

array([ 2,  4,  6,  8, 10, 12, 14, 16])

__Solution-2__

In [13]:
arr71 = np.linspace(2, 16, 8, dtype=int)
arr71

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

__Solution-1__

In [14]:
arr8 = np.arange(25).reshape(5, 5)
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

__Solution-2__     __(List Comprehension)__

In [15]:
arr81 = np.full([1, 25], [i for i in range(25)]).reshape(5, 5)
arr81      

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [16]:
arr9 = np.linspace(0, 24, 25, dtype=int).reshape(5, 5)
arr9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [17]:
arr10 = np.random.rand(5)
arr10

array([0.48228036, 0.66924751, 0.41577485, 0.59499053, 0.24921025])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [18]:
arr11 = np.random.randn(5, 5)
arr11

array([[ 1.02228972, -0.96941062,  0.48905199, -1.55394702, -1.80418111],
       [-1.12747924,  1.1794353 , -0.38939546, -1.24302673,  0.30417712],
       [ 0.91222295, -0.5391884 , -0.367443  , -0.99064632, -0.26531207],
       [ 1.03770066, -2.10900181,  0.8611577 , -0.38083577,  0.02452576],
       [-0.11027661,  0.6406802 , -1.74875664,  0.8155948 ,  0.12669475]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

__Solution-1__

In [19]:
arr12 = np.random.randint(20, 50, size=[3, 4])
arr12

array([[49, 21, 27, 36],
       [39, 22, 35, 32],
       [30, 36, 39, 35]])

__Solution-2__

In [20]:
arr123 = np.random.randint(20, 50, [3, 4])
arr123

array([[30, 42, 38, 40],
       [46, 31, 23, 43],
       [48, 24, 23, 32]])

__Solution-3__

In [21]:
arr121 = np.random.randint(20, 50, size=(12,)).reshape(3, 4)
arr121

array([[48, 36, 47, 31],
       [30, 39, 21, 43],
       [39, 37, 35, 23]])

__Solution-4__

In [22]:
arr122 = np.random.randint(20, 50, 12).reshape(3, 4)
arr122

array([[31, 32, 48, 40],
       [37, 42, 30, 21],
       [28, 37, 29, 49]])

#### 13. Reshape the array below with the shape of 6x8

In [23]:
ranarr1 = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [24]:
ranarr1

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [25]:
ranarr1 = ranarr1.reshape(6, 8)
ranarr1

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [26]:
#reshape with -1
ranarr2 = ranarr1.reshape(-1).reshape(4,12)
ranarr2

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [27]:
#Create array below
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

__Solution-1__

In [28]:
mat1 = mat[1:3, 1:3]
mat1

array([[ 6,  7],
       [10, 11]])

__Solution-2__

In [29]:
mat2= mat[1 : 3, [1, 2]] # slicing + fancy indexing
mat2

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [32]:
mat3 = mat[:, 0]
mat3

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

__Solution-1__

In [35]:
mat4 = mat[1, ::2]
mat4

array([5, 7])

__Solution-2__

In [36]:
mat5 = mat[1, [0, 2]]
mat5

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [46]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [84]:
mat[: , 2] = 77

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

__Solution-1__   

In [65]:
x = mat[1,0]
y = mat[3,1]
mat6 = np.hstack([x,y])    # w/ hstack method
mat6

array([ 5, 14])

__Solution-2__

In [51]:
mat7 = mat[[1,3],[0,1]]
mat7

array([ 5, 14])

__Solution-3__

In [50]:
mat8 = [[mat[1][0], mat[3][1]]]
mat8

[[5, 14]]

__Solution-4__

In [57]:
mat9 = [[mat[1, 0], mat[-1,1]]]
mat9

[[5, 14]]

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [66]:
mat11 = mat[1::2, ::2]
mat11

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [85]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [86]:
mat[mat < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [87]:
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [88]:
mat_sum = mat[mat < 10] + mat[mat > 12]
mat_sum

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

__Solution-1__

In [90]:
mat_std = np.std(mat_sum)
mat_std

29.700546274093877

__Solution-2__

In [91]:
mat_std2 = np.sqrt(np.var(mat_sum))
mat_std2

29.700546274093877

#### 22. Get the sum of the second column from array above

In [92]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [93]:
mat_sum2 = mat[:, 1].sum()
mat_sum2

32

#### 23. Get the median, mean and std of 3rd row from array above

In [96]:
mat = np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [99]:
matt = mat[2]

In [100]:
#median
matt_median = np.median(matt)
matt_median 

10.5

__Solution-1__

In [101]:
#mean
matt_mean = np.mean(matt)
matt_mean 

10.5

__Solution-2__

In [102]:
matt_mean2 = matt.mean()
matt_mean2 

10.5

In [103]:
#std
matt_std = matt.std()
matt_std

1.118033988749895

# Pandas Section

In [104]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [106]:
sal = pd.read_csv('Salaries.csv')
sal.head()    # the first 5 rows

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [107]:
sal.info()       # df info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [108]:
sal.describe()       # df statistical measurements

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year values are there?**

__Solution-1__

In [109]:
sal[["Year"]].value_counts()   # DataFrame

Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

__Solution-2__

In [110]:
sal["Year"].value_counts()    # Series

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

__Solution-3__

In [113]:
sal.groupby(["Year"])['Id'].count()

Year
2011    36159
2012    36766
2013    37606
2014    38123
Name: Id, dtype: int64

**Print out max and avg Totalpay**

In [119]:
#max
sal[['TotalPay']].max()

TotalPay    567595.43
dtype: float64

In [120]:
#avg
sal['TotalPay'].mean()

74768.321971703

**How many records in the TotalPay column are there bigger than avg TotalPay**

__Solution-1__  __(w/ count() attribute)__

In [123]:
sal[sal["TotalPay"] > sal["TotalPay"].mean()]["TotalPay"].count()

69489

__Solution-2__  __(w/ size attribute)__

In [124]:
sal[sal["TotalPay"] > sal["TotalPay"].mean()]["TotalPay"].size

69489

**How much does ALBERT PARDINI make (including benefits)?**

__Solution-1__

In [125]:
sal[sal["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

__Solution-2__  __(w/ loc)__

In [128]:
sal.loc [sal["EmployeeName"]=="ALBERT PARDINI"][["TotalPayBenefits"]]

TotalPayBenefits
2         335279.91

__Solution-3__  

In [134]:
sal.loc[sal["EmployeeName"]=="ALBERT PARDINI", "TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

__Solution-4__ __(w/ iloc)__

In [139]:
sal.loc[sal["EmployeeName"]=="ALBERT PARDINI"]

Id    EmployeeName                         JobTitle    BasePay  \
2   3  ALBERT PARDINI  CAPTAIN III (POLICE DEPARTMENT)  212739.13   

   OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
2    106088.18   16452.6       NaN  335279.91         335279.91  2011    NaN   

          Agency  Status  
2  San Francisco     NaN

In [136]:
sal.iloc[[2]][["TotalPayBenefits"]] # DataFrame

TotalPayBenefits
2         335279.91

**Who is the lowest paid person?**

__Solution-1__ 

In [143]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()][["EmployeeName"]]

EmployeeName
148653    Joe Lopez

__Solution-2__ 

In [144]:
sal[sal["TotalPayBenefits"]==sal["TotalPayBenefits"].min()][["EmployeeName", "TotalPayBenefits"]]

EmployeeName  TotalPayBenefits
148653    Joe Lopez           -618.13

**What are the unique Jobs in dataset?**

__Solution-1__ 

In [146]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

__Solution-2__ 

In [147]:
sal["JobTitle"].value_counts()

Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ... 
CHIEF HOUSING INSPECTOR                              1
TRAFFIC SIGNAL OPERATOR                              1
COURT COMPUTER FACILITIES COORDINATOR                1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
VICTIM & WITNESS TECHNICIAN                          1
Name: JobTitle, Length: 2159, dtype: int64

__Solution-3__ 

In [148]:
sal["JobTitle"].nunique()

2159

**List 3 the least common Jobs**

In [149]:
sal["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

__Solution-1__ __(w/ len())__

In [153]:
len(sal[(sal['Year']==2012) & (sal['TotalPayBenefits'] > sal['TotalPayBenefits'].mean())])

20366

__Solution-2__ 

In [155]:
sal[(sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())].shape[0]

20366

__Solution-3__  __(w/ count())__

In [156]:
sal[ (sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())]['EmployeeName'].count()

20366

**How many people have a title of Manager in their jobs?**

__Solution-1__  __(w/ apply(func))__

In [170]:
#use apply function here
def finder(item):
    if 'MANAGER'.lower() in item.lower(): return True
    else: return False

In [171]:
sal["JobTitle"][sal["JobTitle"].apply(finder)].count()

4110

__Solution-1__  __(w/ apply(func) + lambda)__

In [173]:
sal["JobTitle"][sal["JobTitle"].apply(lambda x: finder(x))].size

4110

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [174]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [175]:
sal_new = sal.iloc[:, [0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [ ]:
sal_new3 = sal_new.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new3

**Print out the names of the employees who earn more than min, but less than avg**

In [176]:
sal[(sal["TotalPayBenefits"].min() < sal["TotalPayBenefits"]) & ( sal["TotalPayBenefits"] < sal["TotalPayBenefits"].mean())][["EmployeeName"]]

EmployeeName
10806          KWE LEE
10807   MIGUEL CARO JR
10808    JOANNE MORRIS
10809    LAYLA WELBORN
10810          LE BANH
...                ...
148648     Leon Walker
148649   Roy I Tillery
148650    Not provided
148651    Not provided
148652    Not provided

[75649 rows x 1 columns]

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___